### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by jaylac2000** [thund3rboi/SkyRanksReborn#1]
add tab list that shows rank and also removed player from the tab list if they vanish them self with any vanish plugin so you may need to make it so if /vanish is rank it does that because everyone has their own form of /vanish

**Comment by thund3rboi** [comment]
This will be in the next update! Thanks for the suggestion, expect it to rollout tomorrow :D

**Comment by thund3rboi** [comment]
Update added, thanks for the suggestion

**Comment by thund3rboi** [comment]
Check the download page for the new update
