### ISSUE TITLE
I cant do anything

### ISSUE THREAD

**Issue by jaylac2000** [thund3rboi/SkyRanksReborn#2]
I can't do anything without getting disconnected for "spam" if i do /sr gui nothing happens than if i do /sr create OWNER it kicks me

![image](https://user-images.githubusercontent.com/53111006/80284243-5c2b4e80-86eb-11ea-9366-84349db6a8d9.png)

**Comment by thund3rboi** [comment]
Just updated the plugin with the new permissions features, please give this a shot and open a new issue if it continues.

**Comment by jaylac2000** [comment]
i have

**Comment by thund3rboi** [comment]
I just uploaded the new version like 20 seconds ago...

**Comment by jaylac2000** [comment]
still getting kicked for "spam" could you possibly add config for ranks like a ranks.yml

**Comment by thund3rboi** [comment]
Is the gui and things like that still not opening? Or is it just spawn? I can't really do anything about the spam its probably a plugin you have. I never got kicked for spam. All the ranks and other data is in a file called data.yml.

**Comment by jaylac2000** [comment]
not sure i have 4 plugins and i dont think its any of them since im testing this on my hub . my java server is not yet released

**Comment by thund3rboi** [comment]
Okay, well not sure then. Every time I've used it I have never got kicked for AFK, opped and not opped.

**Comment by jaylac2000** [comment]
its not afk kick its disconnected for apparently spamming and i have no antispam plugin. SkyRanks, EasyScoreboard, ViaVersion, PlaceholderAPI, ServerSelectorX, LobbyOptionsPlus

**Comment by thund3rboi** [comment]
Sorry yeah meant spam

**Comment by jaylac2000** [comment]
im only having this issue with this plugin

**Comment by thund3rboi** [comment]
I don’t know man, I have 0 issues with it. You probably have something’s setup doing this.

**Comment by jaylac2000** [comment]
could it be something on bungee or spigot?

**Comment by thund3rboi** [comment]
Maybe

**Comment by jaylac2000** [comment]
i have an idea, but i need to know if u have a bungeecord server or not

**Comment by jaylac2000** [comment]
ok, so it is a bungeecord issue. the plugin works fine on my other servers except doesnt work on my lobby, therefore it is a bungee issue
